version: '3.8'

services:
  db:
    image: postgres
    container_name: node_dbpg_1
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/full.sql:/docker-entrypoint-initdb.d/full.sql
    restart: always
    env_file:
      - postgres.env

  web:
    image: web_node-node
    container_name: node_web_node_1
    ports:
      - "8080:8080"
    env_file:
      - node.env
    depends_on:
      - db
